---------------------------------------------------------
-- Balanced Pantheons v0.1
-- Author: KonatsuSV
-- Translation: (EN, CN)KonatsuSV
---------------------------------------------------------

---------------------------------------------------------
-- Dance of the Aurora, Desert Folklore, Sacred Path
---------------------------------------------------------
INSERT INTO BeliefModifiers
VALUES	
('BELIEF_DANCE_OF_THE_AURORA','DANCE_OF_THE_AURORA_CULTURETUNDRAADJACENCY'),
-- ('BELIEF_DANCE_OF_THE_AURORA','DANCE_OF_THE_AURORA_CULTURETUNDRAHILLSADJACENCY'),
('BELIEF_DESERT_FOLKLORE','DESERT_FOLKLORE_PRODUCTIONDESERTADJACENCY'),
-- ('BELIEF_DESERT_FOLKLORE','DESERT_FOLKLORE_PRODUCTIONDESERTHILLSADJACENCY'),
('BELIEF_SACRED_PATH','SACRED_PATH_GOLDFEATUREADJACENCY');

INSERT INTO Modifiers(ModifierId,ModifierType,SubjectRequirementSetId)
VALUES 
('DANCE_OF_THE_AURORA_CULTURETUNDRAADJACENCY','MODIFIER_ALL_CITIES_TERRAIN_ADJACENCY','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
-- ('DANCE_OF_THE_AURORA_CULTURETUNDRAHILLSADJACENCY','MODIFIER_ALL_CITIES_TERRAIN_ADJACENCY','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
('DESERT_FOLKLORE_PRODUCTIONDESERTADJACENCY','MODIFIER_ALL_CITIES_TERRAIN_ADJACENCY','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
-- ('DESERT_FOLKLORE_PRODUCTIONDESERTHILLSADJACENCY','MODIFIER_ALL_CITIES_TERRAIN_ADJACENCY','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
('SACRED_PATH_GOLDFEATUREADJACENCY','MODIFIER_ALL_CITIES_FEATURE_ADJACENCY','CITY_FOLLOWS_PANTHEON_REQUIREMENTS');

INSERT INTO ModifierArguments(ModifierId,Name,Type,Value)
VALUES
('DANCE_OF_THE_AURORA_CULTURETUNDRAADJACENCY','DistrictType','ARGTYPE_IDENTITY','DISTRICT_THEATER'),
('DANCE_OF_THE_AURORA_CULTURETUNDRAADJACENCY','TerrainType','ARGTYPE_IDENTITY','TERRAIN_TUNDRA'),
('DANCE_OF_THE_AURORA_CULTURETUNDRAADJACENCY','YieldType','ARGTYPE_IDENTITY','YIELD_CULTURE'),
('DANCE_OF_THE_AURORA_CULTURETUNDRAADJACENCY','Amount','ARGTYPE_IDENTITY',1),
('DANCE_OF_THE_AURORA_CULTURETUNDRAADJACENCY','Description','ARGTYPE_IDENTITY','LOC_DISTRICT_TUNDRA_FAITH'),
/* ('DANCE_OF_THE_AURORA_CULTURETUNDRAHILLSADJACENCY','DistrictType','ARGTYPE_IDENTITY','DISTRICT_THEATER'),
('DANCE_OF_THE_AURORA_CULTURETUNDRAHILLSADJACENCY','TerrainType','ARGTYPE_IDENTITY','TERRAIN_TUNDRA_HILLS'),
('DANCE_OF_THE_AURORA_CULTURETUNDRAHILLSADJACENCY','YieldType','ARGTYPE_IDENTITY','YIELD_CULTURE'),
('DANCE_OF_THE_AURORA_CULTURETUNDRAHILLSADJACENCY','Amount','ARGTYPE_IDENTITY',1),
('DANCE_OF_THE_AURORA_CULTURETUNDRAHILLSADJACENCY','Description','ARGTYPE_IDENTITY','LOC_DISTRICT_DESERT_FAITH'), */
('DESERT_FOLKLORE_PRODUCTIONDESERTADJACENCY','DistrictType','ARGTYPE_IDENTITY','DISTRICT_INDUSTRIAL_ZONE'),
('DESERT_FOLKLORE_PRODUCTIONDESERTADJACENCY','TerrainType','ARGTYPE_IDENTITY','TERRAIN_DESERT'),
('DESERT_FOLKLORE_PRODUCTIONDESERTADJACENCY','YieldType','ARGTYPE_IDENTITY','YIELD_PRODUCTION'),
('DESERT_FOLKLORE_PRODUCTIONDESERTADJACENCY','Amount','ARGTYPE_IDENTITY',1),
('DESERT_FOLKLORE_PRODUCTIONDESERTADJACENCY','Description','ARGTYPE_IDENTITY','LOC_DISTRICT_DESERT_FAITH'),
/*('DESERT_FOLKLORE_PRODUCTIONDESERTHILLSADJACENCY','DistrictType','ARGTYPE_IDENTITY','DISTRICT_INDUSTRIAL_ZONE'),
('DESERT_FOLKLORE_PRODUCTIONDESERTHILLSADJACENCY','TerrainType','ARGTYPE_IDENTITY','TERRAIN_DESERT_HILLS'),
('DESERT_FOLKLORE_PRODUCTIONDESERTHILLSADJACENCY','YieldType','ARGTYPE_IDENTITY','YIELD_PRODUCTION'),
('DESERT_FOLKLORE_PRODUCTIONDESERTHILLSADJACENCY','Amount','ARGTYPE_IDENTITY',1),
('DESERT_FOLKLORE_PRODUCTIONDESERTHILLSADJACENCY','Description','ARGTYPE_IDENTITY','LOC_DISTRICT_TUNDRA_FAITH'), */
('SACRED_PATH_GOLDFEATUREADJACENCY','DistrictType','ARGTYPE_IDENTITY','DISTRICT_COMMERCIAL_HUB'),
('SACRED_PATH_GOLDFEATUREADJACENCY','FeatureType','ARGTYPE_IDENTITY','FEATURE_JUNGLE'),
('SACRED_PATH_GOLDFEATUREADJACENCY','YieldType','ARGTYPE_IDENTITY','YIELD_GOLD'),
('SACRED_PATH_GOLDFEATUREADJACENCY','Amount','ARGTYPE_IDENTITY',1),
('SACRED_PATH_GOLDFEATUREADJACENCY','Description','ARGTYPE_IDENTITY','LOC_DISTRICT_JUNGLE_FAITH');

---------------------------------------------------------
-- Lady of the Marshes, God of the Open Sky, Goddess of the Hunt
---------------------------------------------------------
INSERT INTO BeliefModifiers
VALUES
('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES','LADY_OF_THE_REEDS_FAITH');
-- ('BELIEF_GOD_OF_THE_OPEN_SKY','GOD_OF_THE_OPEN_SKY_PASTURE_FAITH'),
-- ('BELIEF_GODDESS_OF_THE_HUNT','GODDESS_OF_THE_HUNT_CAMP_FAITH');

INSERT INTO Modifiers(ModifierId,ModifierType,SubjectRequirementSetId)
VALUES
('LADY_OF_THE_REEDS_FAITH','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
('LADY_OF_THE_REEDS_FAITH_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_REEDS_REQUIREMENTS');
-- ('GOD_OF_THE_OPEN_SKY_PASTURE_FAITH','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
-- ('GOD_OF_THE_OPEN_SKY_PASTURE_FAITH_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_PASTURE_REQUIREMENTS'),
-- ('GODDESS_OF_THE_HUNT_CAMP_FAITH','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
-- ('GODDESS_OF_THE_HUNT_CAMP_FAITH_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_CAMP_REQUIREMENTS');

INSERT INTO ModifierArguments(ModifierId,Name,Type,Value)
VALUES
('LADY_OF_THE_REEDS_FAITH','ModifierId','ARGTYPE_IDENTITY','LADY_OF_THE_REEDS_FAITH_MODIFIER'),
('LADY_OF_THE_REEDS_FAITH_MODIFIER','YieldType','ARGTYPE_IDENTITY','YIELD_FAITH'),
('LADY_OF_THE_REEDS_FAITH_MODIFIER','Amount','ARGTYPE_IDENTITY',1);
-- ('GOD_OF_THE_OPEN_SKY_PASTURE_FAITH','ModifierId','ARGTYPE_IDENTITY','GOD_OF_THE_OPEN_SKY_PASTURE_FAITH_MODIFIER'),
-- ('GOD_OF_THE_OPEN_SKY_PASTURE_FAITH_MODIFIER','YieldType','ARGTYPE_IDENTITY','YIELD_FAITH'),
-- ('GOD_OF_THE_OPEN_SKY_PASTURE_FAITH_MODIFIER','Amount','ARGTYPE_IDENTITY',1),
-- ('GODDESS_OF_THE_HUNT_CAMP_FAITH','ModifierId','ARGTYPE_IDENTITY','GODDESS_OF_THE_HUNT_CAMP_FAITH_MODIFIER'),
-- ('GODDESS_OF_THE_HUNT_CAMP_FAITH_MODIFIER','YieldType','ARGTYPE_IDENTITY','YIELD_FAITH'),
-- ('GODDESS_OF_THE_HUNT_CAMP_FAITH_MODIFIER','Amount','ARGTYPE_IDENTITY',1);

UPDATE ModifierArguments
SET VALUE = 2
WHERE (Name = 'Amount'
AND ( /*ModifierId = 'LADY_OF_THE_REEDS_PRODUCTION_MODIFIER' 
OR*/ ModifierId = 'GODDESS_OF_THE_HUNT_CAMP_FOOD_MODIFIER' 
OR ModifierId = 'GOD_OF_THE_OPEN_SKY_PASTURE_CULTURE_MODIFIER'));

---------------------------------------------------------
-- River Goddess
---------------------------------------------------------
UPDATE ModifierArguments
SET VALUE = 4
WHERE (Name = 'Amount'
AND ModifierId = 'RIVER_GODDESS_HOLY_SITE_AMENITY_MODIFIER');

---------------------------------------------------------
-- Fertility Rites
---------------------------------------------------------
UPDATE ModifierArguments
SET VALUE = 15
WHERE (Name = 'Amount'
AND ModifierId = 'FERTILITY_RITES_GROWTH');

---------------------------------------------------------
-- Initiation Rites
---------------------------------------------------------
UPDATE ModifierArguments
SET VALUE = 100
WHERE (Name = 'Amount'
AND ModifierId = 'INITIATION_RITES_FAITH_DISPERSAL_MODIFIER');

---------------------------------------------------------
-- God of Healing
---------------------------------------------------------
UPDATE ModifierArguments
SET VALUE = 300
WHERE (Name = 'Amount'
AND ModifierId = 'GOD_OF_HEALING_UNIT_HEALING_MODIFIER');

---------------------------------------------------------
-- Religious Settlements
---------------------------------------------------------
UPDATE ModifierArguments
SET VALUE = 20
WHERE (Name = 'Amount'
AND (ModifierId = 'RELIGIOUS_SETTLEMENTS_CULTUREBORDER'
OR ModifierId like '%MONUMENT_TO_THE_GODS%'));

---------------------------------------------------------
-- Goddess of the Harvest
---------------------------------------------------------
UPDATE ModifierArguments
SET VALUE = 150
WHERE (Name = 'Amount'
AND (ModifierId = 'GODDESS_OF_THE_HARVEST_HARVEST_MODIFIER'
OR ModifierId = 'GODDESS_OF_THE_HARVEST_REMOVE_FEATURE_MODIFIER'));

---------------------------------------------------------
-- God of War
---------------------------------------------------------
UPDATE ModifierArguments
SET VALUE = 100
WHERE (Name = 'PercentDefeatedStrength'
AND ModifierId = 'GOD_OF_WAR_FAITH_KILLS_MODIFIER');

---------------------------------------------------------
-- God of the Sea, Religious Idols, Gods of the Craftsmen, Oral Traditions, Goddess of Festivals
---------------------------------------------------------
UPDATE ModifierArguments
SET VALUE = 2
WHERE (Name = 'Amount'
AND (ModifierId = 'GOD_OF_THE_SEA_FISHINGBOATS_PRODUCTION_MODIFIER'
OR ModifierId = 'RELIGIOUS_IDOLS_BONUS_MINE_FAITH_MODIFIER'
OR ModifierId = 'RELIGIOUS_IDOLS_LUXURY_MINE_FAITH_MODIFIER'
OR ModifierId = 'GOD_OF_CRAFTSMEN_STRATEGIC_MINE_PRODUCTION_MODIFIER'
OR ModifierId = 'GODDESS_OF_FESTIVALS_PLANTATION_TAG_FOOD_MODIFIER'
OR ModifierId = 'ORAL_TRADITION_PLANTATION_TAG_CULTURE_MODIFIER'));

---------------------------------------------------------
-- Stone Circles
---------------------------------------------------------
INSERT INTO BeliefModifiers
VALUES
('BELIEF_STONE_CIRCLES','STONE_CIRCLES_QUARRY_CULTURE');
-- ('BELIEF_STONE_CIRCLES','STONE_CIRCLES_QUARRY_SCIENCE');

INSERT INTO Modifiers(ModifierId,ModifierType,SubjectRequirementSetId)
VALUES 
('STONE_CIRCLES_QUARRY_CULTURE','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
('STONE_CIRCLES_QUARRY_CULTURE_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_QUARRY_REQUIREMENTS');
-- ('STONE_CIRCLES_QUARRY_SCIENCE','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
-- ('STONE_CIRCLES_QUARRY_SCIENCE_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_QUARRY_REQUIREMENTS');

INSERT INTO ModifierArguments(ModifierId,Name,Type,Value)
VALUES
('STONE_CIRCLES_QUARRY_CULTURE','ModifierId','ARGTYPE_IDENTITY','STONE_CIRCLES_QUARRY_CULTURE_MODIFIER'),
-- ('STONE_CIRCLES_QUARRY_SCIENCE','ModifierId','ARGTYPE_IDENTITY','STONE_CIRCLES_QUARRY_SCIENCE_MODIFIER'),
('STONE_CIRCLES_QUARRY_CULTURE_MODIFIER','YieldType','ARGTYPE_IDENTITY','YIELD_CULTURE'),
('STONE_CIRCLES_QUARRY_CULTURE_MODIFIER','Amount','ARGTYPE_IDENTITY',1);
-- ('STONE_CIRCLES_QUARRY_SCIENCE_MODIFIER','YieldType','ARGTYPE_IDENTITY','YIELD_SCIENCE'),
-- ('STONE_CIRCLES_QUARRY_SCIENCE_MODIFIER','Amount','ARGTYPE_IDENTITY',1);

UPDATE ModifierArguments
SET Value = 1
WHERE (Name = 'Amount'
AND ModifierId = 'STONE_CIRCLES_QUARRY_FAITH_MODIFIER');

















